// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xiwdcnvxpsveuayechtc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhpd2RjbnZ4cHN2ZXVheWVjaHRjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODM1Mzg2NTYsImV4cCI6MjA5OTExNDY1Nn0.wZSXeJWTTQtCeCV-a7nhg2uj6-evI8EfsF6WPNAdFxQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});